version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
networks:
  my_network: